apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-fastapi
  template:
    metadata:
      labels:
        app: ml-fastapi
    spec:
      containers:
        - name: ml-fastapi
          image: ml-fastapi:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ml-fastapi-service
spec:
  selector:
    app: ml-fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
