name: Build and Deploy to K8s

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ml-fastapi:latest .

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/deployment.yaml
